// AUTO-GENERATED by scripts/make-icons.js — do not edit.
export const AVATAR_MAP: Record<number, Record<string, Record<string, number>>> = {
  1: {
    g: {
      round: require('../../assets/avatars/s1_g_round.png'),
      tall: require('../../assets/avatars/s1_g_tall.png'),
      chunky: require('../../assets/avatars/s1_g_chunky.png'),
    },
    b: {
      round: require('../../assets/avatars/s1_b_round.png'),
      tall: require('../../assets/avatars/s1_b_tall.png'),
      chunky: require('../../assets/avatars/s1_b_chunky.png'),
    },
    r: {
      round: require('../../assets/avatars/s1_r_round.png'),
      tall: require('../../assets/avatars/s1_r_tall.png'),
      chunky: require('../../assets/avatars/s1_r_chunky.png'),
    },
  },
  2: {
    g: {
      round: require('../../assets/avatars/s2_g_round.png'),
      tall: require('../../assets/avatars/s2_g_tall.png'),
      chunky: require('../../assets/avatars/s2_g_chunky.png'),
    },
    b: {
      round: require('../../assets/avatars/s2_b_round.png'),
      tall: require('../../assets/avatars/s2_b_tall.png'),
      chunky: require('../../assets/avatars/s2_b_chunky.png'),
    },
    r: {
      round: require('../../assets/avatars/s2_r_round.png'),
      tall: require('../../assets/avatars/s2_r_tall.png'),
      chunky: require('../../assets/avatars/s2_r_chunky.png'),
    },
  },
  3: {
    g: {
      round: require('../../assets/avatars/s3_g_round.png'),
      tall: require('../../assets/avatars/s3_g_tall.png'),
      chunky: require('../../assets/avatars/s3_g_chunky.png'),
    },
    b: {
      round: require('../../assets/avatars/s3_b_round.png'),
      tall: require('../../assets/avatars/s3_b_tall.png'),
      chunky: require('../../assets/avatars/s3_b_chunky.png'),
    },
    r: {
      round: require('../../assets/avatars/s3_r_round.png'),
      tall: require('../../assets/avatars/s3_r_tall.png'),
      chunky: require('../../assets/avatars/s3_r_chunky.png'),
    },
  },
  4: {
    g: {
      round: require('../../assets/avatars/s4_g_round.png'),
      tall: require('../../assets/avatars/s4_g_tall.png'),
      chunky: require('../../assets/avatars/s4_g_chunky.png'),
    },
    b: {
      round: require('../../assets/avatars/s4_b_round.png'),
      tall: require('../../assets/avatars/s4_b_tall.png'),
      chunky: require('../../assets/avatars/s4_b_chunky.png'),
    },
    r: {
      round: require('../../assets/avatars/s4_r_round.png'),
      tall: require('../../assets/avatars/s4_r_tall.png'),
      chunky: require('../../assets/avatars/s4_r_chunky.png'),
    },
  },
  5: {
    g: {
      round: require('../../assets/avatars/s5_g_round.png'),
      tall: require('../../assets/avatars/s5_g_tall.png'),
      chunky: require('../../assets/avatars/s5_g_chunky.png'),
    },
    b: {
      round: require('../../assets/avatars/s5_b_round.png'),
      tall: require('../../assets/avatars/s5_b_tall.png'),
      chunky: require('../../assets/avatars/s5_b_chunky.png'),
    },
    r: {
      round: require('../../assets/avatars/s5_r_round.png'),
      tall: require('../../assets/avatars/s5_r_tall.png'),
      chunky: require('../../assets/avatars/s5_r_chunky.png'),
    },
  },
};
